#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Slack chat-bot Lambda handler.
"""

import os
import logging
import urllib
import random
from simple_sentiment import Sentiment 
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth
from awsconfig import ESHOST, REGION
from nocheckin import aws_access_key_id,aws_secret_access_key
from nocheckin import BOT_TOKEN

SLACK_URL = "https://slack.com/api/chat.postMessage"
min_score=2
host = ESHOST
region = REGION
sentiment = Sentiment("subjclueslen1-HLTEMNLP05.tff")

awsauth = AWS4Auth(aws_access_key_id, aws_secret_access_key, region, 'es')

es = Elasticsearch(
    hosts=[{'host': host, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection
)


def lambda_handler(data, context):
    """Handle an incoming HTTP request from a Slack chat-bot.
    """
    # Grab the Slack event data.
    if "challenge" in data:
        return data["challenge"]
    
    slack_event = data['event']
    # We need to discriminate between events generated by 
    # the users, which we want to process and handle, 
    # and those generated by the bot.
    if "bot_id" in slack_event:
        logging.warn("Ignore bot event")
        logging.warn(str(data))
    else:
        # Get the text of the message the user sent to the bot,
        # and reverse it.
        text = slack_event["text"]
        even = {'msg':text , 'index':'clara', "field":'pkey',"res":"res", "score":0.95  }
        response = kbhandler(even)
        if response.strip() == '' :
            response = "sorry~ don't know how to response --> " + text

        evaluateSentiment = sentiment.weight_by_string(text)
        print(evaluateSentiment)
        if evaluateSentiment <= -4 and evaluateSentiment >= -8 :
            response = "I feel that you are a bit emotional \n"
        if evaluateSentiment < -8 :
            response = "I feel that you have an emotional breakdown, take a deep breath \n"
        if evaluateSentiment > 4 :
            response = "I am always happy to talk to you :) \n"
        
        # Get the ID of the channel where the message was posted.
        channel_id = slack_event["channel"]
        
        # We need to send back three pieces of information:
        #     1. The response
        #     2. The channel id of the private, direct chat (channel)
        #     3. The OAuth token required to communicate with 
        #        the API (token)
        # Then, create an associative array and URL-encode it, 
        # since the Slack API doesn't not handle JSON (bummer).
        data = urllib.parse.urlencode(
            (
                ("token", BOT_TOKEN),
                ("channel", channel_id),
                ("text", response)
            )
        )
        data = data.encode("ascii")
        
        # Construct the HTTP request that will be sent to the Slack API.
        request = urllib.request.Request(
            SLACK_URL, 
            data=data, 
            method="POST"
        )
        # Add a header mentioning that the text is URL-encoded.
        request.add_header(
            "Content-Type", 
            "application/x-www-form-urlencoded"
        )
        
        # Fire off the request!
        urllib.request.urlopen(request).read()

    # Everything went fine.
    return "200 OK"






def kbhandler(even):
# even structure
# {'msg','' , 'index':'testi',
#  "field":'pkey',"res":"res", 
#  "score":2  } #min_score

    msg = even['msg']
    field = even['field']
    idx = even['index']
    if "score" in even:
        min_score = int(even['score'])

    q = {
      "min_score": min_score,
      "query" :{
      "multi_match" : {
        "query": msg, 
        "fields": [ field]
      }
      }
    }   

    res = es.search(index=idx, body=q)
    print("Got %d Hits:" % res['hits']['total'])
    allposi =[]
    allposiScore =[]
    cntPossible = 0
    result = ""
    for h in res['hits']['hits']:
        print(h)
        result = h['_source']['res'][0]
        break

    return result


if __name__ == '__main__':

    import sys
    msg = sys.argv[1]
    even = {'msg':msg , 'index':'clara', "field":'pkey',"res":"res", "score":0.9}
    r = kbhandler(even)
    print("==== result ===")
    print(r)
